---
whitelistObjectNames:
- "*:type=GlobalRequestProcessor,*"
- "*:type=ThreadPool,*"
- "*:type=Manager,*"
- "java.lang:type=Memory,*"
- "java.lang:type=Runtime,*"
- "java.lang:type=OperatingSystem,*"
- "java.lang:type=Threading,*"
